title: Open Coding 
description: "Class of 2026"
owner_name: John Mortensen
github_username: jm1021 
github_repo: "ComputerCrashers_Lessons" 
baseurl: "/ComputerCrashers_Lessons" 
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/open-coding-society" }
    - { platform: x, user_url: "https://x.com/Open_Coding" }
    - { platform: youtube, user_url: "https://www.youtube.com/@OpenCodingSociety" } 
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - navigation/logintoolkit.md